# Generated by Django 5.0.4 on 2024-04-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0002_song_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='movie',
            new_name='album',
        ),
    ]
