# Generated by Django 5.0.4 on 2024-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0005_watchlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlater',
            name='video_id',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
